config/routes.rb
Cocina::Application.routes.draw do

  resources :recipes do
    get :print, :on => :member             #/recipes/1/print
    get :search_title, :on => :collection  #for auto-complete
    post :rate, :on => :member             #/recipes/1/rate?rating=4
    post :move, :on => :member             #/recipes/1/move?cat_id=4&tag=chicken
    get :tags, :on => :collection          #recipes/tags for auto-complete
    get :cats, :on => :collection          #recipes/cats for left nav
    get :indx, :on => :collection          #recipes/indx
    resources :photos do                   #/recipes/1/photos
        get :setprimary, :on => :member
    end
  end 
  
  match 'categories/:category_id/recipes' => 'recipes#by_category', :as => :recipes_by_category, :via => :get
  match 'categories/:category_id/tags/:tag/recipes' => 'recipes#by_category_and_tag', :as => :recipes_by_category_and_tag, :via => :get
        
  namespace :admin do
    resources :categories do
      post :reorder, :on => :collection   
      post :tagname, :on => :collection
      get :tagmaint, :on => :collection
    end
    resources :scarfers do
      post :dotest, :on => :collection
      get :export, :on => :member
      post :import, :on => :collection
    end
    resources :preferences do
      get :editaccount, :on => :collection
      post :updateaccount, :on => :collection
    end
    resources :users
  end 
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end  

  root :to => 'recipes#index'
  

  
  

  

end

app/models/scarfer.rb
class Scarfer < ActiveRecord::Base
  validates_presence_of :name, :source_name, :url_match

  def url_match_qualified
    url_match.upcase.start_with?('HTTP') \
        ? url_match \
        : 'http://' + url_match
  end
  
  def update_attributes_from_yaml(yaml_obj)
    self.name = yaml_obj.name
    self.url_match = yaml_obj.url_match
    self.source_name = yaml_obj.source_name
    self.title = yaml_obj.title
    self.description = yaml_obj.description
    self.ingredients = yaml_obj.ingredients
    self.instructions = yaml_obj.instructions
    self.photo = yaml_obj.photo
    self.time_to_make = yaml_obj.time_to_make
    self.servings = yaml_obj.servings
  end
  
  def self.get_with_regex(url)
    all.each do |scarfer|
      scarfer_url = scarfer.url_match
      p scarfer_url
      if url.match(scarfer_url)        
        return scarfer
      else
        p 'no match'
      end      
    end
    return nil
  end
  
  def self.from_json(json)
    ActiveSupport::JSON.decode(json.gsub("\n",''))
  end
  
end

app/controllers/admin/scarfers_controller.rb
require 'recipescarfer'

class Admin::ScarfersController < ApplicationController

    before_filter :authenticate_is_admin, :except => [:index, :show]
    layout 'admin'
  
    def new
        @scarfer = Scarfer.new
    end
    
    def create
        @scarfer = Scarfer.new(params[:scarfer])
        
        if @scarfer.save
          redirect_to admin_scarfers_path, :notice => 'Scarfer was successfully created.'
        else
          render :action => "new" 
        end 
    end
    
    def edit
        @scarfer = Scarfer.find(params[:id])
    end
    
    def update
        @scarfer = Scarfer.find(params[:id])
    
        if @scarfer.update_attributes(params[:scarfer])
            redirect_to admin_scarfers_path, :notice => 'Scarfer was successfully updated.' 
        else
          render :action => "edit" 
        end
    end
    
    def destroy
        @scarfer = Scarfer.find(params[:id])
        if @scarfer.destroy
          redirect_to admin_scarfers_path, :notice => 'Scarfer was successfully removed.'
        else
          redirect_to admin_scarfers_path, :notice => 'Scarfer was NOT successfully removed.'
        end 
    end
    
    def export
        @scarfer = Scarfer.find(params[:id])
        send_data @scarfer.to_yaml, :filename => @scarfer.name.gsub(' ', '_') + '.yaml'
    end
    
    def import
        y = params[:yaml_file].read
        @scarfer = Scarfer.new
        @scarfer.update_attributes_from_yaml(YAML::load(y))
        render :action => "new"
    end
    
    def index
        @scarfers = Scarfer.all
    end
    
    def show
        @scarfer = Scarfer.find(params[:id])
    end
    
    def dotest
        json = params['jsonstr']
        url = params['url']
        
        settings = Scarfer.from_json(json)
        recipe_scarfer = RecipeScarfer.new(params['url'])
        
        result = 'no result'
        
        begin
            result = recipe_scarfer.getSection(settings)
        rescue => e
            result = e.message
        end
        render :text => result.lstrip.rstrip
    end    

end

app/helpers/scarfers_helper.rb
module ScarfersHelper    
end

app/views/admin/scarfers/_form.html.erb
<%= form_for([:admin, @scarfer], :class => 'form-vertical') do |f| %>

<div>

    <fieldset>
      <% if @scarfer.errors.any? %>    
          <% @scarfer.errors.full_messages.each do |msg| %>
            <div class="alert alert-error"><%= msg %></div>
          <% end %>  
      <% end %>
    </fieldset>
    
    <div id="admin-scarfer-testresults" title="Test Results">
      <pre id="admin-scarfer-testresults-val">Test results will show here...</pre>
    </div>
    
    <fieldset class="control-group">          
      <%= label_tag('Test URL', nil, :class => "control-label") %> 
      <div class="controls">
        <%= text_field_tag 'testurl', 'http://allrecipes.com/recipe/hearty-vegetable-lasagna/', :class => 'span8' %> 
      </div> 
    </fieldset>        
    
    <hr/>
    
    <fieldset class="control-group<%=' error' if @scarfer.errors.messages[:name]%>">
      <%= label_tag('Scarfer Name', nil, :class => "control-label") %> 
      <div class="controls">
        <%= f.text_field :name, :class => 'span8 focused' %> 
      </div>
    </fieldset> 

    <fieldset class="control-group<%=' error' if @scarfer.errors.messages[:source_name]%>">
      <%= label_tag('Source Name (shows as recipe source)', nil, :class => "control-label") %> 
      <div class="controls">
        <%= f.text_field :source_name, :class => 'span8' %> 
      </div>
    </fieldset>      
    
    <fieldset class="control-group<%=' error' if @scarfer.errors.messages[:url_match]%>">
      <%= label_tag('Source url match (ex. allrecipes.com)', nil, :class => "control-label") %> 
      <div class="controls">
        <%= f.text_field :url_match, :class => 'span8' %> 
      </div>
    </fieldset> 

    <fieldset class="control-group">
      <%= label_tag('Example value for sections below', nil, :class => "control-label") %>   
<pre>
{ 
"node_path": "css: span.ingredients",
"section_template": "&lt;ol&gt;~&lt;/ol&gt;",
"item_template": "&lt;li&gt;~&lt;/li&gt;",
"attribute": "src",
"subs": [
  {"token":"x", "replace": "y"},
  {"token":"a", "replace": "b"}
  ]
}
</pre>
    </fieldset>
    
    <fieldset class="control-group">
      <%= label_tag('Title', nil, :class => "control-label") %>           
      <div class="controls">
        <%= f.text_area :title, :rows => '8', :class => 'span8' %><a href="#" class="btn test-btn" id="title">Test</a>
      </div>
    </fieldset> 

    <fieldset class="control-group">
      <%= label_tag('Description', nil, :class => "control-label") %> 
      <div class="controls">
        <%= f.text_area :description, :rows => '8', :class => 'span8' %><a href="#" class="btn test-btn" id="description">Test</a>
      </div>
    </fieldset> 
    
    <fieldset class="control-group">
      <%= label_tag('Photo', nil, :class => "control-label") %>           
      <div class="controls">
        <%= f.text_area :photo, :rows => '8', :class => 'span8' %><a href="#" class="btn test-btn" id="photo">Test</a>
      </div>
    </fieldset> 
    
    <fieldset class="control-group">
      <%= label_tag('Ingredients', nil, :class => "control-label") %>           
      <div class="controls">
        <%= f.text_area :ingredients, :rows => '8', :class => 'span8' %><a href="#" class="btn test-btn" id="ingredients">Test</a> 
      </div>
    </fieldset> 

    <fieldset class="control-group">
      <%= label_tag('Instructions', nil, :class => "control-label") %>           
      <div class="controls">
        <%= f.text_area :instructions, :rows => '8', :class => 'span8' %><a href="#" class="btn test-btn" id="instructions">Test</a> 
      </div>
    </fieldset> 
    
    <fieldset class="control-group">
      <%= label_tag('Time to make', nil, :class => "control-label") %> 
      <div class="controls">
        <%= f.text_area :time_to_make, :rows => '8', :class => 'span8' %><a href="#" class="btn test-btn" id="time_to_make">Test</a>
      </div>
    </fieldset> 
            
    <fieldset class="control-group">
      <%= label_tag('Servings', nil, :class => "control-label") %> 
      <div class="controls">
        <%= f.text_area :servings, :rows => '8', :class => 'span8' %><a href="#" class="btn test-btn" id="servings">Test</a>
      </div>
    </fieldset> 
    
    <%=submit_tag @scarfer.id ? 'Update Scarfer' : 'Create Scarfer', :class => 'btn btn-primary' %>
            
  </div>  <!-- /recipe-view -->

<% end %>

app/views/admin/scarfers/edit.html.erb
<h1>Scarfers :: Editing Scarfer <strong><%=@scarfer.name%></strong></h1>

<%=render 'form' %>

app/views/admin/scarfers/index.html.erb
<h1>Scarfers</h1>
<h5>Scarfers pull in recipe details from other web sites</h5>

<% if current_user.is_admin %>
<div id="admin-scarfer-import" title="Import Scarfer">
  <%= form_tag(import_admin_scarfers_path, :multipart => true, :method => :post) do %>
      <fieldset class="control-group">
      <%= label_tag('Select the yaml file containing the exported scarfer', nil, :class => "control-label") %> 
        <div class="controls">
          <%= file_field_tag :yaml_file %>
        </div>
        <div class="controls">
          <%= submit_tag 'Import', :class => 'btn btn-primary' %>
        </div>
      </fieldset>          
  <% end %>  
</div>
<% end %>

<div class="rounded-container">
  <ul>
    <% @scarfers.each do |scarfer| %>
      <li>
        <%= link_to admin_scarfer_path(scarfer), :title => 'Show' do %><i class="icon-eye-open"></i><% end %>
        <% if current_user.is_admin %>
          <%= link_to(edit_admin_scarfer_path(scarfer), :title => 'Edit') do %><i class="icon-edit"></i><% end %>
          <%= link_to(admin_scarfer_path(scarfer), :confirm => 'Are you sure?', :method => :delete, :title => 'Remove') do %><i class="icon-trash"></i><% end %>      
          <%= link_to(export_admin_scarfer_path(scarfer), :title => 'Export') do %><i class="icon-share-alt"></i><% end %>          
        <% end %>
        &nbsp;<strong><%= scarfer.name %></strong> (<%=link_to scarfer.url_match, scarfer.url_match_qualified, :target => '_blank' %>)
      </li>
    <% end %>
  </ul>
  <% if current_user.is_admin %>
    <div class="admin-list-action"><%= link_to "Create a new scarfer", new_admin_scarfer_path %>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#" id="admin-scarfer-import-btn">Import a scarfer from file</a></div>
  <% end %>
</div>

<br/><br/>
Bookmarklet -&gt; &nbsp;<a href="javascript:(function(){ window.open('<%=new_recipe_url%>?url=' + encodeURIComponent(location.href)); })();">+ Recipe</a>

app/views/admin/scarfers/new.html.erb
<h1>Scarfers :: New Scarfer</h1>

<%=render 'form' %>

app/views/admin/scarfers/show.html.erb
<h1>Scarfers :: <%=@scarfer.name %></h1>

<div class="rounded-container">
  <p>URL Match: <strong><%=@scarfer.url_match %></strong></p>
  <p>Source Name: <strong><%=@scarfer.source_name %></strong></p>
  <p><em>Created on <%=@scarfer.created_at.strftime("%m/%d/%Y") %><%= ' and updated on ' + @scarfer.updated_at.strftime("%m/%d/%Y") if @scarfer.created_at.strftime("%m/%d/%Y") != @scarfer.updated_at.strftime("%m/%d/%Y") %></em></p>
</div>

<span>Title</span>
<pre><%=@scarfer.title %></pre>
<span>Description</span>
<pre><%=@scarfer.description %></pre>
<span>Ingredients</span>
<pre><%=@scarfer.ingredients %></pre>
<span>Instructions</span>
<pre><%=@scarfer.instructions %></pre>
<span>Photo</span>
<pre><%=@scarfer.photo %></pre>
<span>Time to make</span>
<pre><%=@scarfer.time_to_make %></pre>
<span>Servings</span>
<pre><%=@scarfer.servings %></pre>