config/routes.rb
Cocina::Application.routes.draw do

  resources :recipes do
    get :print, :on => :member             #/recipes/1/print
    get :search_title, :on => :collection  #for auto-complete
    post :rate, :on => :member             #/recipes/1/rate?rating=4
    post :move, :on => :member             #/recipes/1/move?cat_id=4&tag=chicken
    get :tags, :on => :collection          #recipes/tags for auto-complete
    get :cats, :on => :collection          #recipes/cats for left nav
    get :indx, :on => :collection          #recipes/indx
    resources :photos do                   #/recipes/1/photos
        get :setprimary, :on => :member
    end
  end 
  
  match 'categories/:category_id/recipes' => 'recipes#by_category', :as => :recipes_by_category, :via => :get
  match 'categories/:category_id/tags/:tag/recipes' => 'recipes#by_category_and_tag', :as => :recipes_by_category_and_tag, :via => :get
        
  namespace :admin do
    resources :categories do
      post :reorder, :on => :collection   
      post :tagname, :on => :collection
      get :tagmaint, :on => :collection
    end
    resources :scarfers do
      post :dotest, :on => :collection
      get :export, :on => :member
      post :import, :on => :collection
    end
    resources :preferences do
      get :editaccount, :on => :collection
      post :updateaccount, :on => :collection
    end
    resources :users
  end 
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end  

  root :to => 'recipes#index'
  

  
  

  

end

app/models/recipe.rb
require 'recipescarfer'

class Recipe < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :photos, :dependent => :destroy
  
  validates_presence_of :title
  validates_presence_of :tag_list
  validates_presence_of :time_to_make
  validates :servings, :numericality => { :only_integer => true }
  validates :rating, :numericality => { :only_integer => true }
  
  acts_as_taggable_on :tags
  
  attr_accessible :title, :description, :ingredients, :instructions, :source, :source_detail, :rating, :servings, :time_to_make, :tag_list, :category_id  
  
  def update_with_scarfer(url)
    url = 'http://' + url if !url.upcase.start_with?('HTTP')
    self.source_detail = url
    scarfer = Scarfer.get_with_regex(url)
    if !scarfer
        scarfer = Scarfer.new
        scarfer.title = "{ \"node_path\": \"css: head title\" }"
        scarfer.description = "{ \"node_path\": \"css: meta[@name='description']\", \"attribute\": \"content\" }"
        self.errors.add('Scarfer', " - No scarfer found that matches the given URL: " + url)
    end  
    begin
        recipe_scarfer = RecipeScarfer.new(url)
    rescue => e
        self.errors.add('Scarfer', "couldn't read from url: " + url + ", error: " + e.message)
        return nil
    end
    self.title = importSecion(recipe_scarfer, scarfer.title).lstrip.rstrip
    self.description = importSecion(recipe_scarfer, scarfer.description).lstrip.rstrip
    self.ingredients = importSecion(recipe_scarfer, scarfer.ingredients).lstrip.rstrip
    self.instructions = importSecion(recipe_scarfer, scarfer.instructions).lstrip.rstrip    
    self.servings = importSecion(recipe_scarfer, scarfer.servings).lstrip.rstrip if scarfer.servings != ''
    self.time_to_make = importSecion(recipe_scarfer, scarfer.time_to_make).lstrip.rstrip if scarfer.time_to_make != ''
    self.source = scarfer.source_name  
    photo_url = importSecion(recipe_scarfer, scarfer.photo).lstrip.rstrip if scarfer.photo != ''
    return photo_url
  end
  
  def add_photo_from_url(url)
    return nil if (!url || url == '')
    return 'unable save photo from invalid url: ' + url if !url.upcase.start_with?('HTTP')
    begin
        photo = Photo.new
        photo.source = url
        photo.remote_photo_url = url
        photo.picture_from_url(url)
        return 'unable save photo from: ' + url if !photo.save        
        self.photos << photo
    rescue => e
        return 'unable to get photo from: ' + url + ' because: ' + e.message 
    end
    return nil
  end
  
  def self.search(filter)
    sql = "title LIKE :search_term OR description LIKE :search_term OR instructions LIKE :search_term OR ingredients LIKE :search_term"
    wild_term = '%' + filter[:term] + '%'

    query = (filter[:sort] == 'best' && !filter[:term].empty?) \
        ? Recipe.order("(title LIKE '#{wild_term}') desc, (ingredients LIKE '#{wild_term}') desc") \
        : Recipe.order(sort_clause(filter[:sort]))   
    query = query.where(sql, :search_term => wild_term) unless filter[:term] == ''
    query = query.scoped_by_category_id(filter[:category_id]) unless filter[:category_id].empty?
    query = query.tagged_with(filter[:tag]) unless filter[:tag].empty?
    
    return query.page(filter[:page]).per(filter[:per_page]) 
  end

  def self.search_title(filter)
    sql = "title LIKE :search_term"
    wild_term = '%' + filter[:term] + '%'
    
    query = Recipe.where(sql, :search_term => wild_term).order(sort_clause('alpha'))
    query = query.scoped_by_category_id(filter[:category_id]) unless filter[:category_id].empty?
    query = query.tagged_with(filter[:tag]) unless filter[:tag].empty?
    
    return query
  end
  
  private
  def self.sort_clause(sortkey)
    sort = case sortkey
       when 'date' then 'created_at desc'
       when 'alpha' then 'title asc'
       when 'alphadesc' then 'title desc'
       when 'rating' then 'rating desc'
       when 'best' then 'title asc'
       else 'created_at desc'
    end    
  end
  
  def importSecion(scarfer, json)
    begin    
        return '' if json.blank?
        settings = Scarfer.from_json(json)
        return scarfer.getSection(settings)
    rescue => e
        return e.message
    end
  end  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_filter :get_categories, :only => [:index, :by_category, :by_category_and_tag, :cats, :new, :edit, :create, :update]
  before_filter :get_filters, :except => [:tags, :rate]
  before_filter :get_title, :only => [:index, :by_category, :by_category_and_tag]
  after_filter :invalidate_categories, :only => [:update, :create, :destroy]
  after_filter :invalidate_recipe_count, :only => [:create, :destroy]
  
  # tag auto-complete
  def tags
    render :json => Recipe.tag_counts_on(:tags).where("tags.name LIKE ?", "%#{params[:term]}%").limit(8).order('count desc').map(&:name) 
  end
  
  def cats
    render :partial => 'layouts/left_nav_cats'
  end
  
  # recipe index (all recipes)
  def indx
    @recipes = params['s'] == 's' ? Recipe.order('source asc') : Recipe.order('title asc')
    #render :layout => "two_column"    
  end
  
  # /recipes
  def index    
    keyword = @filters[:term].strip
    @recipes = Recipe.search(@filters)
    if keyword != '' && @recipes.count == 1
        clear_search_term
        redirect_to @recipes.first       
    else
        render :layout => "two_column"
    end    
  end
    
  # index by category
  def by_category
    category = Category.find(@filters[:category_id])    
    keyword = @filters[:term].strip
    @recipes = Recipe.search(@filters)
    if keyword != '' && @recipes.count == 1
        clear_search_term
        redirect_to @recipes.first       
    else
        render 'index', :layout => "two_column"
    end
  end
  
  # index by category and tag
  def by_category_and_tag
    category = Category.find(@filters[:category_id])    
    keyword = @filters[:term].strip
    @recipes = Recipe.search(@filters)
    if keyword != '' && @recipes.count == 1
        clear_search_term
        redirect_to @recipes.first       
    else
        render 'index', :layout => "two_column"
    end
  end
 
  # search autocomplete (index filter)
  def search_title      
    @recipes = Recipe.search_title(@filters)
    render :json => @recipes.map(&:title)  
  end
 
  # ajax call for star rating
  def rate
    recipe = Recipe.find(params[:id])
    recipe.rating = params['rating']
    recipe.save
    
    respond_to do |format|
      format.html { render :json => recipe.rating }
      format.json { render :json => recipe.rating }
    end
  end
  
  def move
    recipe = Recipe.find(params[:id])
    cat_id = params['cat_id']
    tag = params['tag']
    recipe.category_id = cat_id unless recipe.category_id == cat_id
    recipe.tag_list = tag if tag
    recipe.save
    invalidate_categories
    render :partial => 'recipe', :locals => { :recipe => recipe }
  end
  
  # delete
  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
  
  # recipes/1
  def show
    @recipe = Recipe.find(params[:id])
    @title = @recipe.title
  end

  # print view
  def print
    @recipe = Recipe.find(params[:id])
    @title = @recipe.title
    render :layout => "print"
  end
  
  # recipes/new
  def new
    @title = 'New Recipe'
    @recipe = Recipe.new
    @recipe.rating = 3
    @recipe.servings = 4
    @recipe.time_to_make = 30
    @recipe.user = current_user
    
    prefs = Preferences.find_by_user_id(current_user.id)
    cat = Category.find(prefs.default_category_id)
    @recipe.category = cat ? cat : Category.find('sort_index').first
    @recipe.tag_list = prefs.default_tag_list
    
    if params['url']      
        @photo_url = @recipe.update_with_scarfer(params['url'])    
        if prefs.import_action == 'show'            
            if @recipe.save
                redirect_to @recipe, :notice => @recipe.add_photo_from_url(@photo_url)
            end
        end
    end    
  end
  
  # /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
    @title = 'Edit :: ' + @recipe.title
  end
  
  # create recipe
  def create
    @recipe = Recipe.new(params[:recipe])
    @recipe.tag_list << params['new_tag_text'].to_s.strip if params['new_tag_checkbox'] && params['new_tag_text'].to_s.strip != ''
    @photo_url = params['photo_url']
    @recipe.user = current_user    
    n = 'The recipe was successfully created.'
    
    if @recipe.save
        photo_msg = @recipe.add_photo_from_url(@photo_url)
        n += photo_msg if photo_msg
        redirect_to @recipe, :notice => n
    else
        render :action => "new"
    end
  end
  
  # update recipe
  def update
    @recipe = Recipe.find(params[:id])
    
    if @recipe.update_attributes(params[:recipe])
      if params['new_tag_checkbox'] && params['new_tag_text'].to_s.strip != ''
        @recipe.tag_list << params['new_tag_text'].to_s.strip
        @recipe.save
      end
      redirect_to @recipe, :notice => 'The recipe was successfully updated.' 
    else
      render :action => "edit" 
    end
  end
 
  private
    
  def get_val(key, default_val)
    return params[key] if params[key]
    return session[:filters][key] if session[:filters] && session[:filters][key]
    return default_val
  end
  
  def set_val(key, val)
    @filters = default_filter unless @filters
    @filters[key] = val    
  end
  
  def get_title
    cat_name = @filters[:category_id].empty? ? '' : Category.find(@filters[:category_id]).name
    @title = 'All Recipes' if @filters[:category_id].empty? && @filters[:tag].empty?
    @title = "#{cat_name}" if !@filters[:category_id].empty? && @filters[:tag].empty?
    @title = "#{cat_name} :: #{@filters[:tag].capitalize}" if !@filters[:category_id].empty? && !@filters[:tag].empty?    
    @title += " :: filtered by '#{@filters[:term]}'" if !@filters[:term].empty?
  end
  
  def get_filters     
    # reset session filter if we've navigated to a different categoy or tag or done a global search
    session[:filters] = nil if params['all'] || params['category_id'] || params['tag'] || params['url'] || params['globalterm']
    
    # get/set values
    term = get_val(:term, '')
    set_val(:term, get_val(:globalterm, term))
    set_val(:page, params[:page] ||= '1')
    set_val(:per_page, get_val(:per_page, current_user.preferences.per_page))
    set_val(:category_id, get_val(:category_id, ''))
    set_val(:tag, get_val(:tag, ''))
    set_val(:sort, get_val(:sort, 'date'))
    set_val(:sort, 'best') unless @filters[:term].empty?
    
    # save to session
    session[:filters] = @filters
  end
  
  def default_filter
    return { 
       :category_id => '',
       :tag => '',
       :term => '',
       :sort => 'date',
       :page => '1',
       :per_page => current_user.preferences.per_page
      }
  end
  
  def clear_search_term
    # if there was an exact match, we need to clear the search term to avoid infinte loop to recipe details
    session[:filters][:term] = '' if session[:filters]        
  end   
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_details.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<% if !is_print %>
<div class="page-nav">
  <a class="btn" href="<%=recipes_url %>"><i class="icon-chevron-left"></i>&nbsp;Recipe List</a>            
  <a class="btn" href="<%=edit_recipe_path(@recipe) %>"><i class="icon-edit"></i>&nbsp;Edit</a>        
  <%= link_to(recipe_path(@recipe), :confirm => 'Are you sure?', :method => :delete, :class => "btn") do %><i class="icon-trash"></i>&nbsp;Remove<% end %>      
  <a class="btn" href="<%=recipe_photos_path(@recipe)%>"><i class="icon-picture"></i>&nbsp;Photos</a>
  <a class="btn" href="<%=print_recipe_path(@recipe) %>"><i class="icon-print"></i>&nbsp;Print View</a>       
</div>
<% end %>

<h1><%=@recipe.title %></h1>

<% if @recipe.description %>
<div class="recipe-description recipe-section">
  <%=@recipe.description %>
</div>
<% end %>

<% photo_count = is_print ? 0 : @recipe.photos.length %>
<% if photo_count > 0 %>
  <% allphotos = @recipe.photos.order('is_primary desc').order('created_at desc') %>
  <div class="recipe-image recipe-section">
      <table><tr>
          <td>
            <%= image_tag allphotos[0].photo.url(:medium), :id => 'bigimage', :class => 'big-image' %>
          </td>
          <% if photo_count > 1 %>
            <% i = 0 %>
            <td>
              <% allphotos.each do |photo| %>
                <% if i == 3 %></td><td><% end %>
                <a href='#' class="thumb-link" rel="<%=photo.photo.url(:medium) %>"><img src="<%=photo.photo.url(:thumb) %>" alt="" class='thumb'/></a> 	
                <br/>  
                <% i += 1 %>
              <% end %>                 
            </td>
          <% end %>
      </tr></table>
  </div>
<% end %>

<div class="recipe-yield recipe-section">
     <i class="icon-hand-right"></i>&nbsp;Servings: <%=@recipe.servings %> 
     <br/>
     <i class="icon-hand-right"></i>&nbsp;Preparation Time: <%=@recipe.time_to_make %>
</div>            

<div class="row">
    <div class="span12 recipe-card">
        <div class="span4" style="margin-left: 0px;">        
            <div class="left-half">
                <h2>Ingredients</h2>
                <div class="recipe-ingredients recipe-section">
                    <%=raw @recipe.ingredients %>             
                </div> 
            </div>
        </div>
        <div class="span8" style="margin-left: 0px;">
            <div class="right-half">
              <h2>Instructions</h2>
              <div class="recipe-instructions recipe-section">
                  <%=raw @recipe.instructions %>               
              </div>
            </div>
        </div>
    </div>
</div>

<div class="recipe-meta recipe-section">
    Filed under: <%=link_to @recipe.category.name, recipes_by_category_url(:category_id => @recipe.category.id) %> :: 
      <%=@recipe.tags.collect{|tag| link_to tag.name, recipes_by_category_and_tag_url(:category_id => @recipe.category.id, :tag => tag.name)}.join(', ').html_safe %><br>
    <% if @recipe.source_detail != '' || @recipe.source != '' %>
      Source:               
        <% if @recipe.source_detail.start_with?("http") %>
          <a href="<%=@recipe.source_detail%>"><%=@recipe.source != '' ? @recipe.source : @recipe.source_detail %>&nbsp;<i class="icon-globe"></i></a>
        <% else %>
          <%=@recipe.source %><%= ', ' if @recipe.source_detail != '' %><em><%=@recipe.source_detail %></em>
        <% end %><br>
    <% end %>
    Created on <%=@recipe.created_at.strftime("%m/%d/%Y") %> by kevboo 
    <%= ' and updated on ' + @recipe.updated_at.strftime("%m/%d/%Y") if @recipe.created_at.strftime("%m/%d/%Y") != @recipe.updated_at.strftime("%m/%d/%Y") %>
</div>

app/views/recipes/_form.html.erb
<%= form_for(@recipe, :class => 'form-vertical', :id => 'recipe_form') do |f| %>

  <% if @recipe.id %>
    <div class="page-nav">
        <% if params['f'] == 'i' %>
          <a class="btn" href="<%=recipes_path%>"><i class="icon-chevron-left"></i>&nbsp;Recpice list</a>
        <% else %>
          <a class="btn" href="<%=recipe_path(@recipe)%>"><i class="icon-chevron-left"></i>&nbsp;Back to recipe</a> 
        <% end %>
        <%=submit_tag 'Save Changes', :class => 'btn' %>    
    </div>
  <% else %>
    <div class="page-nav">
      <a class="btn" href="<%=recipes_path%>"><i class="icon-chevron-left"></i>&nbsp;Recpice list</a>    
      <%=submit_tag 'Create Recipe', :class => 'btn' %>      
      <a class="btn" href="#" id="import_nav_btn"><i class="icon-download-alt"></i>&nbsp;Import recipe details...</a>       
    </div>
  <% end %>
  
  <div class="recipe-view">
    
    <fieldset>
      <% if @recipe.errors.any? %>    
          <% @recipe.errors.full_messages.each do |msg| %>
            <div class="alert alert-error"><%= msg %></div>
          <% end %>  
      <% end %>
    </fieldset>

    <fieldset class="control-group<%=' error' if @recipe.errors.messages[:title]%>">
      <%= label_tag(:title, nil, :class => "control-label") %> 
      <div class="controls">
        <%= f.text_field :title, :class => 'span8 focused' %> 
      </div>
    </fieldset> 

     <fieldset class="control-group">
      <%= label_tag(:category_id, nil, :class => "control-label") %> 
      <div class="controls">
        <%= f.select(:category_id, options_from_collection_for_select(Category.all, "id", "name", @recipe.category_id)) %>
      </div>
    </fieldset>              

     <fieldset class="control-group<%=' error' if @recipe.errors.messages[:tag_list]%>">
      <%= label_tag('Sub-categories', nil, :class => "control-label") %> 
      <div class="controls">        
        <% recipe_tags = @recipe.tags.map { |t| t.name } %>        
        <% @categories.each do |category| %>
          <div class="category-tags-select" style="display:<%=@recipe.category_id==category[:id] ? 'block' : 'none'%>;" id="category-tag-section-<%=category[:id]%>">
            <% 
              tag_count = category[:tags].length 
              #half = tag_count > 3 ? (tag_count / 2) + (tag_count % 2) + 1 : tag_count + 1
              half = (tag_count / 2) + (tag_count % 2) + 1
              curr = 1
            %>
            <table class="sub-categories"><tr><td>
            <% category[:tags].each do |tag| %>
              <% if curr == half %>
                </td><td>
              <% end %>
              <% curr += 1 %>
              <input type="checkbox" data-cat="<%=category[:id]%>" id="recipe_tag_list_<%=category[:id]%>_<%=tag[:name].sub(/ /, '')%>" name="recipe[tag_list][]" value="<%=tag[:name]%>" <%="checked" if recipe_tags.include?(tag[:name]) && (@recipe.category_id==category[:id]) %>/>
                &nbsp;<label for="recipe_tag_list_<%=category[:id]%>_<%=tag[:name].sub(/ /, '')%>" style="display:inline;"><%=tag[:name]%></label><br/>
            <% end %>
            </td></tr></table>
          </div>
        <% end %>
        <input type="checkbox" id="new_tag_checkbox" name="new_tag_checkbox" value="new_tag_checkbox" style="margin-top: 0px; margin-bottom: 6px;" />
        <%= text_field_tag "new_tag_text", nil, :class => "span3", :style => "padding: 1px; margin-top: 2px;" %>
      </div>
    </fieldset>
    
    <fieldset class="control-group">
      <%= label_tag('Description (optional)', nil, :class => "control-label") %> 
      <div class="controls">
        <%= f.text_area :description, :rows => '2', :class => 'span8' %>
      </div>
    </fieldset> 

    <fieldset class="control-group">
      <%= label_tag(:ingredients, nil, :class => "control-label") %> 
      <div class="controls">
        <%= f.text_area :ingredients, :rows => '8', :class => 'span8' %>
      </div>
    </fieldset> 
    
    <fieldset class="control-group">
      <%= label_tag(:instructions, nil, :class => "control-label") %> 
      <div class="controls">
        <%= f.text_area :instructions, :rows => '8', :class => 'span8' %>
      </div>
    </fieldset> 
       
    <fieldset class="control-group">
      <%= label_tag(:servings, nil, :class => "control-label") %> 
      <div class="controls">
        <%= f.select(:servings, options_for_select((1..25), @recipe.servings)) %>
      </div>
    </fieldset> 

    <fieldset class="control-group<%=' error' if @recipe.errors.messages[:time_to_make]%>">
      <%= label_tag(:time_to_make, nil, :class => "control-label") %> 
      <div class="controls">
        <%= f.text_field :time_to_make, :class => 'span2' %>
      </div>
    </fieldset> 
    
    <fieldset class="control-group">
      <%= label_tag('Source (web site name, book name, etc.)', nil, :class => "control-label") %> 
      <div class="controls">
        <%= f.text_field :source, :class => 'span8' %> 
      </div>
    </fieldset> 
    
    <fieldset class="control-group">
      <%= label_tag('Source Detail (web site url, book page number, etc.)', nil, :class => "control-label") %> 
      <div class="controls">
        <%= f.text_field :source_detail, :class => 'span8' %> 
      </div>
    </fieldset> 
  
    <% if @photo_url %>
        <%=hidden_field_tag 'photo_url', @photo_url%>
    <% end %>
       
    <%=submit_tag @recipe.id ? 'Save Changes' : 'Create Recipe', :class => 'btn btn-primary' %>
    
  </div>  <!-- /recipe-view -->

<% end %>
 
<script type="text/javascript">
  $(document).ready(function() {    
    
    $('#recipe_title').focus();
    
    // ---------------------------------------------------------------
    // Sub-category check box/text field for new tag
    // ---------------------------------------------------------------
    $("#new_tag_text").keyup(function () {
      var cb = $("#new_tag_checkbox");      
      if (jQuery.trim($(this).val()).length > 0){ cb.prop('checked', true); }
      else { cb.prop('checked', false); }
    });
    $("#new_tag_text").change(function () {
      var cb = $("#new_tag_checkbox");      
      if (jQuery.trim($(this).val()).length > 0){ cb.prop('checked', true); }
      else { cb.prop('checked', false); }
    });
    $("#recipe_category_id").change(function(){ 
      var cat_id = $(this).val();
      $(".category-tags-select").hide();
      $("#category-tag-section-" + cat_id).show();
    });
    
    // ---------------------------------------------------------------
    // nicEditor
    // ---------------------------------------------------------------
    new nicEditor({
      fullPanel : true,
      iconsPath : '/assets/nicedit/nicEditorIcons.gif'
     }).panelInstance('recipe_ingredients'); 
     
    new nicEditor({
      fullPanel : true,
      iconsPath : '/assets/nicedit/nicEditorIcons.gif'
     }).panelInstance('recipe_instructions');     
      
    // ---------------------------------------------------------------
    // Save buttons
    // ---------------------------------------------------------------    
    $('form.new_recipe').submit(clearCheckBoxes);
    $('form.edit_recipe').submit(clearCheckBoxes);
    
    function clearCheckBoxes(){
        var cat_id = $("#recipe_category_id").val();
        $('table.sub-categories tbody tr td input:checkbox[data-cat!=' + cat_id +']').prop('checked', false);
        //return false;    
    }
    
  });
</script>

app/views/recipes/_recipe.html.erb
<tr id="recipe-list-row-<%=recipe.id%>">
  <td class="thumb-col">
      <% if recipe.photos.any?
          recipe_thumb = recipe.photos.order('is_primary desc').order('created_at desc')[0]
          recipe_photo_count = recipe.photos.count
          %>  
          <div class="imageSub">
            <%= link_to(recipe) do %>
              <%=image_tag(recipe_thumb.photo.url(:thumb), :class => 'thumb')%>
            <% end %>
            <% if recipe_photo_count > 1 %><div class="blackbg"><%=recipe_photo_count%></div><% end %>
          </div> 
      <% else %>
          <%= link_to(recipe) do %>
              <%=image_tag('nophoto.png', :class => 'thumb')%>
          <% end %>                            
      <% end %>   
  </td>
  <td class="title-col">
      <div class='recipe-list-title draggable_recipe_category' data-id='<%=recipe.id%>' data-catid='<%=recipe.category.id%>'>
          <%= link_to(recipe.title, recipe) %>
      </div>
      <div class='tight'>
        <span>Category: <%=link_to recipe.category.name, recipes_by_category_url(:category_id => recipe.category.id) %> :: 
          <%= recipe.tags.collect{|tag| link_to tag.name, recipes_by_category_and_tag_url(:category_id => recipe.category.id, :tag => tag.name)}.join(', ').html_safe %>                      
        </span>
      </div>
      <div class='tight'>
        <% if recipe.source_detail != '' || recipe.source != '' %>
          <span>Source:               
            <% if recipe.source_detail.start_with?("http") %>
              <a href="<%=recipe.source_detail%>"><%=recipe.source != '' ? recipe.source : recipe.source_detail %></a>
            <% else %>
              <%=recipe.source %><%= ', ' if recipe.source_detail != '' %> <%=recipe.source_detail %> 
            </span><% end %>
        <% end %>
      </div>
  </td>
  <td class="actions-col">
      <div class="recipe-actions" id="recipe_actions_<%=recipe.id%>" style="display:none;">
        <a href="<%=edit_recipe_path(recipe)%>?f=i" rel="tooltip" title="Edit"><i class="icon-edit"></i></a>
        <a href="#" id="delete_<%=recipe.id%>" class="delete-button" rel="tooltip" title="Remove"><i class="icon-trash"></i></a>
        <a href="<%=recipe_photos_path(recipe)%>?f=i" rel="tooltip" title="Manage Photos"><i class="icon-picture"></i></a>
        <a href="<%=print_recipe_path(recipe) %>" rel="tooltip" title="Print View"><i class="icon-print"></i></a>
       </div>
  </td>
</tr>  

app/views/recipes/edit.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<%=render "form" %>

app/views/recipes/indx.html.erb
<h1>Index :: by <%=params['s'] == 's' ? 'Source' : 'Name'%></h1>
<br/>

<% 
prev = '' 
curr = ''
curr_index = 0
half = (get_recipe_count / 2) + 1
time_to_break = false
already_broke = false
%>

<div class="row">
  <div class="span5">
       
      <div>
      <% @recipes.each do |recipe| %>
        <% 
        curr_index += 1 
        time_to_break = true if curr_index > half
        curr = params['s'] == 's' ? recipe.source : recipe.title.first.upcase 
        curr = '[No Source]' if curr == ''
        %>
        <% if curr != prev %>
          <% prev = curr %>    
          </div>
          <% if time_to_break == true && already_broke == false %>
            <% already_broke = true %>
            </div><div class="span5">
          <% end %>
          <div style="margin-bottom: 8px;">
          <h2><%=curr%></h2>
        <% end %>
        <div><%=link_to(recipe.title, recipe)%></div>
      <% end %>
      </div>

  </div>
</div>