config/routes.rb
Cocina::Application.routes.draw do

  resources :recipes do
    get :print, :on => :member             #/recipes/1/print
    get :search_title, :on => :collection  #for auto-complete
    post :rate, :on => :member             #/recipes/1/rate?rating=4
    post :move, :on => :member             #/recipes/1/move?cat_id=4&tag=chicken
    get :tags, :on => :collection          #recipes/tags for auto-complete
    get :cats, :on => :collection          #recipes/cats for left nav
    get :indx, :on => :collection          #recipes/indx
    resources :photos do                   #/recipes/1/photos
        get :setprimary, :on => :member
    end
  end 
  
  match 'categories/:category_id/recipes' => 'recipes#by_category', :as => :recipes_by_category, :via => :get
  match 'categories/:category_id/tags/:tag/recipes' => 'recipes#by_category_and_tag', :as => :recipes_by_category_and_tag, :via => :get
        
  namespace :admin do
    resources :categories do
      post :reorder, :on => :collection   
      post :tagname, :on => :collection
      get :tagmaint, :on => :collection
    end
    resources :scarfers do
      post :dotest, :on => :collection
      get :export, :on => :member
      post :import, :on => :collection
    end
    resources :preferences do
      get :editaccount, :on => :collection
      post :updateaccount, :on => :collection
    end
    resources :users
  end 
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end  

  root :to => 'recipes#index'
  

  
  

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :recipes
  
  validates_uniqueness_of :name
  validates_presence_of :name
  
  before_destroy :validate_no_recipes  
  
  def recipe_tags
    recipes.tag_counts_on(:tags).order('name')
  end
  
  protected
  
  def validate_no_recipes
    if self.recipes.any?
      errors.add('the category', 'cannot be deleted because there are recipes filed under it.')
      return false
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  
  before_filter :authenticate_is_admin
  layout 'admin'
  
  def show
  end
  
  def index
    @categories = Category.order('sort_index')
  end

  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(params[:category])
	  session['categories'] = nil
      redirect_to admin_categories_path, :notice => 'Category was successfully updated.' 
    else
      render :action => "edit" 
    end
  end

  def new
    @category = Category.new
  end

  def create
    max = Category.maximum('sort_index')
    @category = Category.new(params[:category])
    @category.sort_index = max + 1
    
    if @category.save
      session['categories'] = nil
      redirect_to admin_categories_path, :notice => 'Category was successfully created.'
    else
      render :action => "new" 
    end    
  end

  def destroy
    @category = Category.find(params[:id])
    if(params['killemall'])
      Recipe.destroy_all("category_id = #{@category.id}")
    end
    if(params['moveemall'])
      cat_id = params['newcategory']
      @category.recipes.each do |recipe|
        recipe.category_id = cat_id
        recipe.save
      end
      @category = Category.find(params[:id])
    end
    if @category.destroy
      session['categories'] = nil
      redirect_to admin_categories_path, :notice => 'Category was successfully removed.'
    else
      @categories = Category.where("id <> #{@category.id}").order('sort_index')
    end 
  end
  
  def reorder
    cats = Category.all
    cats.each do |cat|
      cat.sort_index = params['category'].index(cat.id.to_s) + 1
      cat.save
    end
    session['categories'] = nil
    render :nothing => true
  end
  
  def tagmaint
  end
  
  def tagname
    oldtag = params['tagname']
    newtag = params['newtag']
    notice = 'nothing was done'
    if !oldtag || !newtag || oldtag.blank? || newtag.blank?
        notice = 'You must specify a tag name and a new tag name'
    else
        newtagobj = Tag.find_by_name(newtag)
        if newtagobj
            # new tag already exists, so remove old one and add new one to recipes
            recipes = Recipe.tagged_with(oldtag)
            recipe_count = recipes.count.to_s
            recipes.each do |recipe|
                recipe.tag_list.remove(oldtag)
                recipe.tag_list << newtag if !recipe.tag_list.include?(newtag)
                recipe.save!
            end
            notice = recipe_count + ' recipes were updated from ' + oldtag + ' to ' + newtag
        else
            oldtagobj = Tag.find_by_name(oldtag)
            if oldtagobj
                oldtagobj.name = newtag
                oldtagobj.save!
                session['categories'] = nil
                notice = 'The tag ' + oldtag + ' was successfully changed to ' + newtag
            else
                notice = 'The specified tag name could not be found.'
            end        
        end
    end
    session['categories'] = nil
    redirect_to tagmaint_admin_categories_path, :notice => notice 
  end
end

app/views/admin/categories/_form.html.erb
<% if @category.errors.any? %>    
    <% @category.errors.full_messages.each do |msg| %>
      <div class="alert alert-error"><%= msg %></div>
    <% end %>  
<% end %>

<div class="rounded-container">  
  <%= form_for([:admin, @category], :class => 'form-horizontal') do |f| %>
  <fieldset>  
    <div class="control-group">
      <%= label_tag(:name, nil, :class => "control-label") %> 
      <div class="controls">
        <%= f.text_field :name, :class => 'input-xlarge focused' %> 
      </div>
    </div>
    <div class="control-group">
      <%= label_tag :description, nil, :class => "control-label" %>  
      <div class="controls">
        <%= f.text_field :description, :class => 'input-xlarge' %>
      </div>
    </div>
    <div>
      <%= f.submit nil, :class => 'btn btn-primary' %>    
    </div>    
  </fieldset>
  <% end %>
</div>

app/views/admin/categories/destroy.html.erb
<h1>Categories :: Remove Category Options</h1>
<h5>Select an option below, or return to the category list</h5>

<% if @category.errors.any? 
  @category.errors.full_messages.each do |msg|  %>
    <div class="alert alert-error"><%= msg %></div>
<% end
end %>

<div class="rounded-container">
  <%= form_for(@category, :url => admin_category_path, :html => { :class => "form-horizontal" }, :method => :delete) do |f| %>
  <fieldset>  
    <div class="control-group">
      <strong>Option 1:</strong> <u>Delete</u> all recipes that are filed under <%=@category.name%>?
    </div>
    <%=hidden_field_tag 'killemall', '1'%>
    <div>
      <%= f.submit 'Yes, delete the recipes', :class => 'btn btn-primary' %>
      &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'No, return to category list.', admin_categories_path %>
    </div>    
  </fieldset>
  <% end %>
</div>

<div class="rounded-container">
  <%= form_for(@category, :url => admin_category_path, :html => { :class => "form-horizontal" }, :method => :delete) do |f| %>
  <fieldset>  
    <div class="control-group">
      <strong>Option 2:</strong> <u>Move</u> all recipes that are filed under <%=@category.name%> to this category:
    </div>
    <%=hidden_field_tag 'moveemall', '1'%>
    <div class="control-group">
      <%=select_tag "newcategory", options_from_collection_for_select(@categories, "id", "name")%>    
    </div>    
    <div>    
      <%= f.submit 'Yes, move the recipes', :class => 'btn btn-primary' %>
      &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'No, return to category list.', admin_categories_path %>
    </div>    
  </fieldset>
  <% end %>
</div>

app/views/admin/categories/edit.html.erb
<h1>Categories :: Editing Category <strong><%=@category.name%></strong></h1>

<%= render 'form' %>

app/views/admin/categories/index.html.erb
<style>
  .handle:hover{cursor: move;}
</style>

<h1>Categories</h1>
<h5>To reorder, click a category name and drag</h5>

<div class="rounded-container">
  <ul id="admin-categories-list">
    <% @categories.each do |category| %>
      <li id="category_<%= category.id %>">
        <%= link_to(edit_admin_category_path(category)) do %><i class="icon-edit"></i><% end %>
        <%= link_to(admin_category_path(category), :confirm => 'Are you sure?', :method => :delete) do %><i class="icon-trash"></i><% end %>      
        &nbsp;<span class="handle"><strong><%= category.name %></strong>&nbsp;<%= '(' + category.description + ')' if (category.description && category.description != '') %></span>
      </li>
    <% end %>
  </ul>
  <div class="admin-list-action"><%= link_to "Add a new category", new_admin_category_path %></div>
</div>

app/views/admin/categories/new.html.erb
<h1>Categories :: New Category</h1>

<%= render 'form' %>

app/views/admin/categories/tagmaint.html.erb
<h1>Tag (sub-category) maintenance</h1>
<h5>To change a tag name, select the current name and enter a new name.  
<br/>This changes the name globally, across categories.</h5>

<div class="rounded-container">
  <%= form_tag(tagname_admin_categories_path, :method => :post, :class => 'form-vertical') do %>
  <fieldset>  
    <div class="control-group">
      <%= label_tag('Tag (sub-category)', nil, :class => "control-label") %> 
      <div class="controls">
        <%=select_tag('tagname', options_from_collection_for_select(Tag.all, "name", "name"), :class => 'span3') %>      
      </div>
    </div>
    <div class="control-group">
      <%= label_tag('New name', nil, :class => "control-label") %> 
      <div class="controls">
        <%=text_field_tag 'newtag', nil, :class => 'span3' %> 
      </div>
    </div>
    <div>
      <%= submit_tag 'Change it', :class => 'btn btn-primary' %>   
    </div> 
  <% end %>
</div>