config/routes.rb
Cocina::Application.routes.draw do

  resources :recipes do
    get :print, :on => :member             #/recipes/1/print
    get :search_title, :on => :collection  #for auto-complete
    post :rate, :on => :member             #/recipes/1/rate?rating=4
    post :move, :on => :member             #/recipes/1/move?cat_id=4&tag=chicken
    get :tags, :on => :collection          #recipes/tags for auto-complete
    get :cats, :on => :collection          #recipes/cats for left nav
    get :indx, :on => :collection          #recipes/indx
    resources :photos do                   #/recipes/1/photos
        get :setprimary, :on => :member
    end
  end 
  
  match 'categories/:category_id/recipes' => 'recipes#by_category', :as => :recipes_by_category, :via => :get
  match 'categories/:category_id/tags/:tag/recipes' => 'recipes#by_category_and_tag', :as => :recipes_by_category_and_tag, :via => :get
        
  namespace :admin do
    resources :categories do
      post :reorder, :on => :collection   
      post :tagname, :on => :collection
      get :tagmaint, :on => :collection
    end
    resources :scarfers do
      post :dotest, :on => :collection
      get :export, :on => :member
      post :import, :on => :collection
    end
    resources :preferences do
      get :editaccount, :on => :collection
      post :updateaccount, :on => :collection
    end
    resources :users
  end 
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end  

  root :to => 'recipes#index'
  

  
  

  

end

app/views/layouts/_footer.html.erb
    <div class="row" id="footer">
        <div class="span12">
            <hr/>
            &copy; Kevin Noone 2012 &nbsp;-=//\\//=-&nbsp; version 1.3.0-<%=render :partial => 'layouts/revision'%>
            <br/><br/>
        </div>
    </div>    
  </body>
</html>

app/views/layouts/_header.html.erb
<!doctype html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <title>La Cocina <%= ' - ' + @title if @title %></title>
    <%= csrf_meta_tags %>    
    <meta name="description" content="La Cocina recipe database"/>
    <meta name="author" content="cleverswine"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
</head>
<body>

app/views/layouts/_left_nav_cats.html.erb
<ul class="left-nav">
    <% @categories.each do |category| %>
      <li class='left_nav_category<%=" active" if @filters[:tag] == '' && @filters[:category_id].to_s == category[:id].to_s %>' data-id='<%=category[:id].to_s%>' data-tag=''>
          <%=link_to category[:name], recipes_by_category_url(:category_id => category[:id])%>
      </li>
      <% category[:tags].each do |tag| %>
        <li class="left_nav_category li-tag<%=' active' if @filters[:tag] == tag[:name] && @filters[:category_id].to_s == category[:id].to_s %>" data-id='<%=category[:id]%>' data-tag='<%=tag[:name]%>'>
          <a href="<%=recipes_by_category_and_tag_url(:category_id => category[:id], :tag => tag[:name])%>">
            <%=tag[:name]%>&nbsp;<span class="tag-count">(<%=tag[:count]%>)</span></a>
        </li>
     <% end %>
  <% end %>    
</ul>

app/views/layouts/_nav.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <%=link_to 'La Cocina', recipes_url, :class => 'brand' %>                
            <% if current_user %>
            <div class="nav-collapse">
                <ul class="nav pull-right">
                    <li>
                      <%=link_to 'Add a new recipe', new_recipe_path %>
                    </li>
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Tools&nbsp;<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><a href="/conversions.html" target="_blank"><i class="icon-adjust"></i>&nbsp;&nbsp;Conversion Chart</a> </li>
                          <li><a href="/substitutes.html" target="_blank"><i class="icon-random"></i>&nbsp;&nbsp;Substitutions</a> </li>
                          <li><a href="<%=admin_scarfers_path%>"><i class="icon-download-alt"></i>&nbsp;&nbsp;View Recipe Scarfers</a></li>
                        </ul>
                    </li>
                    <% if current_user.is_admin %>
                      <li class="dropdown">
                          <a data-toggle="dropdown" class="dropdown-toggle" href="#">Admin&nbsp;<b class="caret"></b></a>
                          <ul class="dropdown-menu">
                            <li><a href="<%=admin_categories_path%>"><i class="icon-tasks"></i>&nbsp;&nbsp;Categories</a></li>
                            <li><a href="<%=tagmaint_admin_categories_path%>"><i class="icon-tags"></i>&nbsp;&nbsp;Tag Maintenance</a></li>                          
                            <li><a href="<%=admin_users_path%>"><i class="icon-user"></i>&nbsp;&nbsp;Registered Users</a></li> 
                            <li><a href="<%=admin_scarfers_path%>"><i class="icon-download-alt"></i>&nbsp;&nbsp;Scarfers</a></li>
                          </ul>
                      </li>
                    <% end %>
                    <li>
                      <form action='<%=recipes_url%>' class='navbar-search pull-right' method='get' id='search_form_global'>
                        <input type='text' placeholder='Search all recipes' class='search-query span3' name='globalterm' id='globalterm' />
                      </form>                
                    </li>                        
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#"><%=current_user.name%>&nbsp;<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<%=edit_admin_preference_path(current_user.id)%>"><i class="icon-user"></i>&nbsp;&nbsp;Preferences</a></li>
                            <li><a href="<%=logout_path%>" data-method="delete" rel="nofollow"><i class='icon-off'></i>&nbsp;&nbsp;Log Out</a></li>
                        </ul>
                    </li>
                </ul>
            </div> <!-- /nav-collapse -->                
            <% end %>            
        </div> <!-- /container -->
    </div> <!-- /navbar-inner -->        
</div>

app/views/layouts/_revision.html.erb
DEVELOPMENT

app/views/layouts/admin.html.erb
<%=render :partial => 'layouts/header'%>    
    
<%=render :partial => 'layouts/nav'%>

<div class="container">

    <div class="row">
      <% if current_user.is_admin %>
      <div class="span3">
          <h2>Admin</h2>
          <ul class="left-nav">
            <li><a href="<%=admin_categories_path%>">Categories</a></li>
            <li><a href="<%=tagmaint_admin_categories_path%>">Tag Maintenance</a></li>                          
            <li><a href="<%=admin_users_path%>">Registered Users</a></li>   
            <li><a href="<%=admin_scarfers_path%>">Scarfers</a></li>          
          </ul>
      </div>
      <% end %>
      <div class="span9">
        <div class="admin">
          <% if flash[:notice] %>
            <div class="alert alert-success"><%= flash[:notice] %></div>
          <% end %>        
          <%= yield %>
        </div>
      </div>
    </div>
    
    <%=render :partial => 'layouts/footer'%>

</div>

app/views/layouts/application.html.erb
<%=render :partial => 'layouts/header'%>    
    
<%=render :partial => 'layouts/nav'%>

<div class="container">
    <div class="row">
      <div class="span12">
        <%= yield %>
      </div>
    </div>
  <%=render :partial => 'layouts/footer'%>    
</div>

app/views/layouts/prefs.html.erb
<%=render :partial => 'layouts/header'%>    
    
<%=render :partial => 'layouts/nav'%>

<div class="container">

    <div class="row">
      <div class="span3">
          <h2>Preferences</h2>
          <ul class="left-nav">
            <li><a href="<%=edit_admin_preference_path(current_user.id)%>">General Settings</a></li>
            <li><a href="<%=editaccount_admin_preferences_path%>">My Account</a></li>  
          </ul>
      </div>
      <div class="span9">
        <div class="admin">
          <% if flash[:notice] %>
            <div class="alert alert-success"><%= flash[:notice] %></div>
          <% end %>        
          <%= yield %>
        </div>
      </div>
    </div>
    
    <%=render :partial => 'layouts/footer'%>

</div>

app/views/layouts/print.html.erb
<!doctype html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <title><%= @title if @title %></title>
    <%= csrf_meta_tags %>    
    <meta name="description" content="kitchen"/>
    <meta name="author" content="cleverswine"/>
    <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <%= stylesheet_link_tag    "application" %>
    <style type="text/css">
      body { padding-top: 20px; }
    </style>
</head>
<body>  
  <div class="container">      
      <div class="row">
        <div class="span12">
          <%= yield %>
        </div>
      </div>
      <%=render :partial => 'layouts/footer'%>    
  </div>
</body>
</html>

app/views/layouts/two_column.html.erb
<%=render :partial => 'layouts/header'%>    
    
<%=render :partial => 'layouts/nav'%>

<div class="container">

    <div class="row">
      <div class="span3">
          <h2>Categories</h2>
          <div id="left_nav_cats">
            <%=render :partial => 'layouts/left_nav_cats'%>
          </div>
          <h2>Index</h2>
          <ul class="left-nav">
              <li<%=" class='active'" if (@filters[:tag] == '' && @filters[:category_id] == '') || params[:all] %>>
                <a href="<%=recipes_path(:all => '1')%>">All Recipes&nbsp;<span class="tag-count">(<%=get_recipe_count%>)</span></a>                
              </li>
              <li class="li-tag"><a href="<%=indx_recipes_path%>">By Name</a></li>
              <li class="li-tag"><a href="<%=indx_recipes_path(:s => 's')%>">By Source</a></li>
          </ul>          
      </div>
      <div class="span9">
        <%= yield %>
      </div>
    </div>
    
    <%=render :partial => 'layouts/footer'%>

</div>